/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.cc.lpoo.cv.gui.pessoa;

/**
 *
 * @author Igor Rocha
 */
public class JPanelPessoaListagem extends javax.swing.JPanel {

    /**
     * Creates new form JPanelPessoaListagem
     */
    public JPanelPessoaListagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFiltro = new javax.swing.JPanel();
        lblFiltro = new javax.swing.JLabel();
        txtfFiltro = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        pnlSul = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        scpRolagem = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFiltro.setText("Filtrar por CPF:");
        pnlFiltro.add(lblFiltro);

        txtfFiltro.setColumns(10);
        pnlFiltro.add(txtfFiltro);

        btnFiltrar.setText("Filtrar");
        pnlFiltro.add(btnFiltrar);

        add(pnlFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        pnlSul.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlSul.add(btnEditar);

        btnRemover.setText("Remover");
        pnlSul.add(btnRemover);

        jButton1.setText("Cancelar");
        pnlSul.add(jButton1);

        add(pnlSul, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 260, 410, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Data de Cadastro", "Nome", "RG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpRolagem.setViewportView(jTable1);

        add(scpRolagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 410, 220));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton jButton1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JPanel pnlFiltro;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JScrollPane scpRolagem;
    private javax.swing.JTextField txtfFiltro;
    // End of variables declaration//GEN-END:variables
}
